sudo: false
language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
services:
    - docker
before_install:
    - docker run --name kafka -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=127.0.0.1 --env ADVERTISED_PORT=9092 spotify/kafka
install:
    - pip install flake8 mock
    - pip install pytest==3.5.1
    - pip install pytest-cov==2.5.1
    - pip install python-coveralls==2.9.1
    - pip install sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs docs/_build
    - python -m sphinx -b html -W docs docs/_build
    - py.test -s -v --cov=kq
after_success:
    - coveralls
